---
- name: Create virtual environment and install numpy
  hosts: all
  become: true
  tasks:
    - name: Install numpy in virtual environment
      ansible.builtin.pip:
        name: numpy
        virtualenv: /user/home/venv
        virtualenv_python: python3.10
