---
- name: Add the line 'module load gcc' to foo's bashrc
  hosts: all
  become: true
  tasks:
    - name: Update bashrc for foo user
      ansible.builtin.lineinfile:
        dest: /home/foo/.bashrc
        line: "module load gcc"
