---
- name: Copy the file /scratch/file.txt to /home/user/data.txt
  hosts: all
  become: true
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        remote_src: True
        src: /scratch/file.txt
        dest: /home/user/data.txt
