---
- name: Delete directory /home/mydata/web
  hosts: all
  become: true
  tasks:
    - name: Delete directory and content
      ansible.builtin.file:
        state: absent
        path: /home/mydata/web
