---
- name: Set permissions under /srv/path
  hosts: all
  become: true
  tasks:
    - name: Make directory tree readable
      ansible.builtin.file:
        path: /srv/path
        mode: u=rwX,g=rX,o=rX
        recurse: yes
