---
- name: Enable passwordless sudo for wheel and create an ansible user in that group
  hosts: all
  become: true
  tasks:
    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present
    - name: Wheel group
      ansible.builtin.group:
        name: wheel
        system: true
        state: present
    - name: Ansible user
      ansible.builtin.user:
        name: ansible
        comment: Ansible User
        groups:
          - wheel
        state: present
    - name: Allow group wheel to sudo
      ansible.builtin.lineinfile:
        path: "/etc/sudoers"
        line: "%wheel	ALL=(ALL:ALL) NOPASSWD:ALL"
        regexp: "^%wheel"
        owner: root
        group: root
        mode: "640"
        state: present
