---
- name: Various postfix configuration tasks
  hosts: redhat,ubuntu
  become: true
  tasks:
    - name: Install postfix
      ansible.builtin.package:
        name: postfix
        state: latest
    - name: Backup original main.cf
      ansible.builtin.copy:
        src: /etc/postfix/main.cf
        dest: /etc/postfix/main.bak
        force: false
        remote_src: true
    - name: Download main.cf
      ansible.builtin.get_url:
        url: "http://example.com/cfg.{{ ansible_distribution | lower }}"
        dest: /etc/postfix/main.cf
        #validate_certs: false
        mode: '644'
        owner: root
        group: root
        force: true
