---
- name: Copy .war files from controller to remote
  hosts: all
  become: true
  tasks:
    - name: Copy war files from controller
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/tmp/"
      with_fileglob:
        - "/backup/*.war"
