---
- name: Move the file /scratch/file.txt to /home/user/data.txt
  hosts: all
  become: true
  tasks:
    - name: Copy file from /scratch/file.txt to /home/user/data.txt
      ansible.builtin.copy:
        remote_src: True
        src: /scratch/file.txt
        dest: /home/user/data.txt
    - name: Remove old file /scratch/file.txt
      ansible.builtin.file:
        path: /scratch/file.txt
        state: absent
