---
- name: Disable password for 'service' user
  hosts: all
  become: true
  tasks:
    - name: Disable password for 'service' user
      ansible.builtin.user:
        name: service
        password: '!'
