---
- name: Clone the 'release1.8.4' branch from the ansible/ansible github repo to /ansible
  tasks:
  - name: Clone git repo
    ansible.builtin.git:
      repo: git@github.com:ansible/ansible.git
      dest: /ansible
      version: release1.8.4
